Repository Hanaro-OMNM/Hanasset-FE, pull requests merged in 2024-12, with the labels that each got.

#119 Proj 89 feat home menu
  package-lock.json
  package.json
  src/assets/img/hanaLogo.png
  src/assets/img/manual/1.png
  src/assets/img/manual/2.png
  src/assets/img/manual/3.png
  src/assets/img/manual/4.png
  src/assets/img/manual/5.png
  src/components/atoms/CloseButton.tsx
  src/components/atoms/ManualImg.tsx
  src/components/atoms/ManualTitle.tsx
  src/components/atoms/RecentCheckedButton.tsx
  src/components/molecules/ManualButton.tsx
  src/components/template/userManual.tsx
  src/pages/LoanRecommned.tsx
  src/pages/Main.tsx
  tailwind.config.js
Labels: enhancement

#121 Proj 92 fix estate data format
  package-lock.json
  package.json
  src/assets/Dummy.tsx
  src/components/template/EditProfileLayout.tsx
  src/components/template/MapLayout/MapLayout.tsx
  src/components/template/MapLayout/MapMarkerCluster.tsx
  src/components/template/MyEstateList.tsx
  src/pages/Main.tsx
  src/pages/RealEstateDetail/RealEstateDetail.tsx
  src/pages/RealEstateDetail/components/BasicInfo.tsx
  src/pages/RealEstateDetail/components/Estimate.tsx
  src/pages/RealEstateDetail/components/ImageCarousel.tsx
  src/pages/RealEstateDetail/components/MarketChart.tsx
  src/pages/RealEstateDetail/components/MarketInfoCard.tsx
  src/pages/RealEstateDetail/components/MarketSection.tsx
  src/pages/RealEstateDetail/components/PropertyDetails.tsx
  src/pages/RealEstateDetail/components/PropertyInfo.tsx
  src/pages/RealEstateDetail/components/Tabs.tsx
  src/pages/RealEstateDetail/components/TransactionTable.tsx
  src/pages/RealEstateDetail/components/TypeInfo.tsx
  src/pages/RealEstateList/RealEstateCard.tsx
  src/pages/RealEstateList/RealEstateList.tsx
  src/types/global.d.ts
  src/utils/DirectionUtils.ts
  src/utils/EntranceYpeUtils.ts
  src/utils/HeatingAndCoolingUtils.ts
Labels: invalid

#131 Proj 101 Normal User Register
  package-lock.json
  package.json
  src/App.tsx
  src/assets/Dummy.tsx
  src/assets/img/login/HanaHappy.png
  src/assets/img/signUp/HanaGreeting.png
  src/components/atoms/ModalInput.tsx
  src/components/molecules/UpcomingConsulting.tsx
  src/components/template/Modal/BirthDateForm.tsx
  src/components/template/Modal/Login.tsx
  src/components/template/Modal/Modal.tsx
  src/components/template/Modal/SignUp.tsx
  src/components/template/Modal/SignUpForm.tsx
  src/components/template/MyEstateList.tsx
  src/components/template/SelectEstate.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/RealEstateDetail/RealEstateDetail.tsx
  src/pages/RealEstateDetail/components/ImageCarousel.tsx
  src/pages/RealEstateDetail/components/MarketChart.tsx
  src/pages/RealEstateDetail/components/MarketInfoCard.tsx
  src/pages/RealEstateDetail/components/MarketSection.tsx
  src/pages/RealEstateDetail/components/TransactionTable.tsx
  src/pages/RealEstateList/RealEstateCard.tsx
  src/pages/RealEstateList/RealEstateList.tsx
  src/pages/reservation/ChatReservation.tsx
  src/pages/reservation/DynamicFormSwitcher.tsx
  src/platform/PlatformAPI.ts
  src/recoil/isLogin/atom.ts
  src/recoil/isLogin/index.ts
  src/recoil/loanReservation/atom.ts
  src/types/hanaAsset.d.ts
  src/types/hanaAssetRequest.common.ts
  src/types/hanaAssetResponse.common.ts
  src/utils/CookieUtils.ts
Labels: feature

#147 Proj 142 관심 지역 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/assets/dongInfo.csv
  src/assets/tmp2.cjs
  src/components/template/Modal/MyLocation.tsx
  src/pages/GuestChatDetail.tsx
  src/pages/LoanDetail.tsx
  src/pages/LoanRecommend.tsx
  src/pages/LoanRecommend/components/LoanRecommendTab.tsx
  src/pages/MyPage.tsx
  src/pages/PropertyAgree.tsx
  src/pages/RealEstateList/RealEstateList.tsx
  src/pages/chat/SemiTitle.tsx
  src/pages/consultant/Consultant.tsx
  src/pages/consultant/GuestDetailInfo.tsx
  src/pages/consultant/GuestInfo.tsx
  src/pages/consultant/GuestWaiting.tsx
  src/pages/location/LocationFiltersD.tsx
  src/pages/location/LocationFiltersG.tsx
  src/pages/search/SearchResult.tsx
  src/platform/PlatformAPI.ts
  src/types/hanaAssetResponse.common.ts
Labels: API

#149 Proj 145 사용자 경험 향상
  src/components/template/MapLayout/MapLayout.tsx
  src/pages/LoanRecommend.tsx
  src/pages/MyPage.tsx
  src/pages/location/LocationFiltersD.tsx
  src/pages/search/SearchResult.tsx
  src/recoil/center/atom.ts
Labels: bug

#152 hot-fix: 채팅 상담 대출 추천 페이지 API 무한 요청 이슈 수정
  src/pages/GuestChatDetail.tsx
  src/pages/LoanRecommend.tsx
Labels: bug
